version: '3.8'

services:
  iris-copilot-plugin:
    build: .
    container_name: iris-copilot-plugin
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - DEBUG=false
      - ENVIRONMENT=production
      - IRIS_API_URL=${IRIS_API_URL:-https://iris.pnj.com.vn}
      - IRIS_API_BASE_URL=${IRIS_API_BASE_URL:-https://iris.pnj.com.vn/api/v1}
      - AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
      - AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET}
      - AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID}
      - AZURE_AD_REDIRECT_URI=${AZURE_AD_REDIRECT_URI:-https://iris.pnj.com.vn/api/v1/azure-ad/callback}
      - PLUGIN_SECRET=${PLUGIN_SECRET}
      - PLUGIN_NAME=${PLUGIN_NAME:-IRIS Teams Copilot}
      - PLUGIN_VERSION=${PLUGIN_VERSION:-1.0.0}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - ENABLE_METRICS=${ENABLE_METRICS:-true}
      - METRICS_PORT=${METRICS_PORT:-9090}
      - CORS_ORIGINS=${CORS_ORIGINS:-["https://iris.pnj.com.vn", "https://copilot.microsoft.com"]}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-100}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-60}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - iris-network

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    container_name: iris-copilot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - iris-network

volumes:
  redis_data:

networks:
  iris-network:
    driver: bridge
