#!/bin/bash

echo "🚀 GitHub Push Helper Script"
echo "============================"
echo ""
echo "📋 HƯỚNG DẪN PUSH LÊN GITHUB TỪ MÁY LOCAL:"
echo ""
echo "1️⃣ Đảm bảo bạn đã download project về máy local"
echo "2️⃣ Mở terminal/command prompt tại thư mục project"
echo "3️⃣ Chạy các lệnh sau:"
echo ""
echo "------- COPY VÀ CHẠY TỪNG DÒNG -------"
echo ""
echo "# Khởi tạo Git"
echo "git init"
echo ""
echo "# Add tất cả files"
echo "git add ."
echo ""
echo "# Tạo commit đầu tiên"
echo 'git commit -m "Initial commit - IRIS Backend v2 with Clean Architecture"'
echo ""
echo "# Đổi branch sang main"
echo "git branch -M main"
echo ""
echo "# Add remote repository"
echo "git remote add origin https://github.com/dungnt2508/iris-backend-v2.git"
echo ""
echo "# Push lên GitHub"
echo "git push -u origin main"
echo ""
echo "------- KẾT THÚC -------"
echo ""
echo "📌 LƯU Ý:"
echo "- Nếu gặp lỗi authentication, dùng Personal Access Token"
echo "- Hoặc dùng GitHub Desktop để push dễ hơn"
echo "- Repository URL: https://github.com/dungnt2508/iris-backend-v2"
echo ""
echo "🔑 Tạo Personal Access Token:"
echo "1. Vào: https://github.com/settings/tokens"
echo "2. Generate new token (classic)"
echo "3. Chọn scope: repo"
echo "4. Copy token và dùng làm password khi push"
echo ""
echo "✅ Good luck!"